version: '3.8'

services:
  web:
    build: django/
    command: sh -c "python manage.py collectstatic --noinput && gunicorn current_task_display.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/app/staticfiles
    expose:
      - 8000
    env_file:
      - .env.prod
  nginx:
    build: nginx/
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/staticfiles

volumes:
  static_volume:
