version: '3.8'

services:
  web:
    build: django/
    command: sh -c "python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    networks:
      - kimai2_default

networks:
  kimai2_default:
    external: true
